// String t is generated by random shuffling string s and then add one more letter at a random position. Return the letter that was added to t.
// Input: s = "abcd", t = "abcde"


function findRandomStr(s = '', t = '') {

    let obj = {}

    for (let index = 0; index < s.length; index++) {
        const char = s[index];
        obj[char] = 1
    }
    console.log({ obj });


    for (let index = 0; index < t.length; index++) {
        const char = t[index];
        if (!(obj[char] == 1)) {
            return char
        }
    }


}
let s = "abcd"
let t = "abcde"

console.log(findRandomStr(s, t));
